#!/usr/bin/env python

################################################################################
##                                                                            ##
## This file is a part of TADEK.                                              ##
##                                                                            ##
## TADEK - Test Automation in a Distributed Environment                       ##
## (http://tadek.comarch.com)                                                 ##
##                                                                            ##
## Copyright (C) 2011 Comarch S.A.                                            ##
## All rights reserved.                                                       ##
##                                                                            ##
## TADEK is free software for non-commercial purposes. For commercial ones    ##
## we offer a commercial license. Please check http://tadek.comarch.com for   ##
## details or write to tadek-licenses@comarch.com                             ##
##                                                                            ##
## You can redistribute it and/or modify it under the terms of the            ##
## GNU General Public License as published by the Free Software Foundation,   ##
## either version 3 of the License, or (at your option) any later version.    ##
##                                                                            ##
## TADEK is distributed in the hope that it will be useful,                   ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with TADEK bundled with this file in the file LICENSE.               ##
## If not, see http://www.gnu.org/licenses/.                                  ##
##                                                                            ##
## Please notice that Contributor Agreement applies to any contribution       ##
## you make to TADEK. The Agreement must be completed, signed and sent        ##
## to Comarch before any contribution is made. You should have received       ##
## a copy of Contribution Agreement along with TADEK bundled with this file   ##
## in the file CONTRIBUTION_AGREEMENT.pdf or see http://tadek.comarch.com     ##
## or write to tadek-licenses@comarch.com                                     ##
##                                                                            ##
################################################################################

import os
import sys
import optparse

from tadek.core import config
config.setProgramName("tadek-ui")

from tadek.core import log

sys.path.insert(0, os.path.join(config.DATA_DIR, "ui"))

import ui

try:
    from PySide import QtGui, QtCore
except ImportError:
    log.critical("Required PySide libraries are not installed")
    sys.exit(2)

USAGE = '''%prog [OPTION]...'''

DESC = '''%prog is an user-frendly UI application providing all TADEK client 
functionalities.'''

if __name__ == "__main__":
    parser = optparse.OptionParser(prog=config.getProgramName(),
                                   usage=USAGE, description=DESC,
                                   version=config.getProgramVersion())
    parser.parse_args()
    # Run the UI program
    app = QtGui.QApplication(sys.argv)
    ui.run()
    sys.exit(app.exec_())

